services:
  web:
    image: php:7.2-apache
    ports:
      - "80:80"
    #develop:
    #  watch:
    #    - action: sync
    #      path: .
    #      target: /src
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.1
    restart: always

# Optionally, define networks if you have more complex requirements
# networks:
#   default:
#     driver: bridge