DROP DATABASE IF EXISTS sparkle;
CREATE DATABASE sparkle;

CREATE TABLE IF NOT EXISTS members (
    
)

CREATE TABLE IF NOT EXISTS blogposts (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    title VARCHAR(100) NOT NULL, 
    content MEDIUMTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);